[build]
    command = "make clean"

[[redirects]]
    from = "/404.html"
    to = "/page/404/index.html"
    status = 302
    force = true

[[redirects]]
    from = "/gentoo_stage3_nmor"
    to = "https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/releases/amd64/autobuilds/current-stage3-amd64-nomultilib-openrc/"
    status = 301
    force = true

# ARI-WEB-SPECIFIC #

[[redirects]]
    from = "/favicon.ico"
    to  = "/favicons/ari-web-ukraine.png"
    status = 200
    force = true

[[redirects]]
    from = "/tinycore"
    to = "https://tcl.ari-web.xyz/"
    status = 301
    force = true

[[redirects]]
    from = "/git/*"
    to = "https://github.com/TruncatedDinosour/website/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/dotfiles/*"
    to = "https://github.com/TruncatedDinosour/dotfiles-cleaned/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/dotfile/:distro/*"
    to = "https://github.com/TruncatedDinosour/dotfiles-cleaned/tree/:distro/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/overlay/*"
    to = "https://github.com/TruncatedDinosour/dinolay/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/gentooatom/*"
    to = "https://github.com/TruncatedDinosour/dinolay/tree/main/:splat"
    status = 301
    force = true

# https://answers.netlify.com/t/how-do-i-do-cross-domain-redirects-to-github-repositories-from-netlify/52258/2?u=b00bleatea
[[redirects]]
    from = "/gh/*"
    to = "https://github.com/TruncatedDinosour/:splat"
    status = 301
    force = true

## BACKWARDS COMPATIBILITY ##

[[redirects]]
    from = "/data/*"
    to = "https://files.ari-web.xyz/files/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/page/blog/*"
    to = "https://blog.ari-web.xyz/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/page/blog"
    to = "https://blog.ari-web.xyz/"
    status = 301
    force = true

####################

[[redirects]]
    from = "/gentoo_stage3_nmorh"
    to = "https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/releases/amd64/autobuilds/current-stage3-amd64-hardened-nomultilib-openrc/"
    status = 301
    force = true

[[redirects]]
    from = "/mp"
    to = "https://www.youtube.com/playlist?list=PL7UuKajElTaChff3BkcJE6620lSuSUaDC"
    status = 301
    force = true

[[redirects]]
    from = "/:page"
    to = "/page/:page"
    status = 302
    force = false

[[redirects]]
    from = "/*"
    to = "/page/404/index.html"
    status = 404
    force = false

[[headers]]
    for = "/*"

    [headers.values]
        X-XSS-Protection = "1; mode=block"
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Frame-Options = "deny"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "upgrade-insecure-requests; reflected-xss; sandbox"

