[build]
    command = "make clean"

[[redirects]]
    from = "/404.html"
    to = "/page/404/index.html"
    status = 200
    force = true

[[redirects]]
    from = "/:page"
    to = "/page/:page"
    force = false

[[redirects]]
    from = "/gentoo_stage3_nmor"
    to = "https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/releases/amd64/autobuilds/current-stage3-amd64-nomultilib-openrc/"
    status = 301
    force = true

[[redirects]]
    from = "/gentoo_stage3_nmorh"
    to = "https://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/releases/amd64/autobuilds/current-stage3-amd64-hardened-nomultilib-openrc/"
    status = 301
    force = true

[[redirects]]
    from = "/git"
    to = "https://github.com/TruncatedDinosour/website"
    status = 301
    force = true

[[redirects]]
    from = "/mail"
    to = "mailto:truncateddinosour@gmail.com"
    status = 301
    force = true

[[redirects]]
    from = "/*"
    to = "/page/404/index.html"
    status = 404
    force = false
